service_name: travis-ci
repo_token: SXAu9LZV5mNHWbVOIaRtuhGOUcYn1kboZ

coverage_clover: build/logs/clover.xml
json_path: build/logs/coveralls-upload.json

coverage_clover: build/logs/clover.xml

coverage_clover: build/logs/clover-*.xml

coverage_clover:
  - build/logs/clover-Auth.xml
  - build/logs/clover-Db.xml
  - build/logs/clover-Validator.xml
  
coveralls --coverage_clover=build/logs/my-clover.xml
